In [ ]:
# To create an artificial neural network
# Define the input
import numpy as np
# sleeping hours and studying hours
x=np.array(([5,9],[6,8],[2,8]),dtype=float)
print(x)
# Define the desire output result
y=np.array(([70],[90],[85]),dtype=float)
print(y)

[[5. 9.]
 [6. 8.]
 [2. 8.]]
[[70.]
 [90.]
 [85.]]


In [ ]:
# scale upto the unit 1
x=x/np.amax(x,axis=0)
y=y/100
print("The X scale upto the unit 1",x)
print("The Y scale upto the unit 1",y)

The X scale upto the unit 1 [[0.83333333 1.        ]
 [1.         0.88888889]
 [0.33333333 0.88888889]]
The Y scale upto the unit 1 [[0.7 ]
 [0.9 ]
 [0.85]]


In [ ]:
# Define an neuralNetwork class
class neuralNetwork:
  def __init__(self):
    self.input=2
    self.hidden=3
    self.output=1

    self.w1=np.random.randn(self.input,self.hidden)
    self.w2=np.random.randn(self.hidden,self.output)

  def Forward(self,x):
    self.z=np.dot(x,self.w1)
    self.z1=self.sigmoid(self.z)
    self.z2=np.dot(self.z1,self.w2)
    output=self.sigmoid(self.z2)
    return output

  def sigmoid(self,s,deriv=False):
    if(deriv==True):
      return s*(1-s)
    return 1/(1+(np.exp(-s)))

  def Backword(self,x,y,output):
    self.output_error=y-output
    self.output_error_delta=self.output_error*self.sigmoid(output,deriv=True)
    self.z2_error=self.output_error_delta*self.sigmoid(self.w2.T)
    self.z2_error_delta=self.z2_error*self.sigmoid(self.z2,deriv=True)

    self.w1+=x.T.dot(self.z2_error_delta)
    self.w2+=self.z2.T.dot(self.output_error_delta)

  def Train(self,x,y):
    output=self.Forward(x)
    self.Backword(x,y,output)

NN=neuralNetwork()

for i in range(1000):
  NN.Train(x,y)

print("The input value is "+str(x))
print("The desire output is "+str(y))
print("The loss is "+str(np.mean(np.square(y-NN.Forward(x)))))
print("The actual output is \n"+str(NN.Forward(x)))


The input value is [[0.83333333 1.        ]
 [1.         0.88888889]
 [0.33333333 0.88888889]]
The desire output is [[0.7 ]
 [0.9 ]
 [0.85]]
The loss is 0.007558862106145081
The actual output is 
[[0.82099585]
 [0.8203857 ]
 [0.80879133]]
