In [ ]:
#pip install tensorflow
import tensorflow as tf
x=tf.constant([1,2,3,4,5,6],shape=[2,3])
print(x)

y=tf.constant([7,8,9,10,11,12],shape=[3,2])
print(y)

z=tf.matmul(x,y) #matrix multiplication
print(z)

matrix=tf.random.uniform([2,2],dtype=tf.float32)
print("Matrix A: \n{} ".format(matrix))
eigen_values,eigen_vectors=tf.linalg.eigh(matrix)
print("Eigen Vectors:\n{}\n\nEigen Values:\n{}\n".format(eigen_vectors,eigen_values))



#e_matrix_A=tf.random.uniform([2,2],minval=3,maxval=10,dtype=tf.float32,name="matrixA")
#print("Matrix A:\n{}\n\n".format(e_matrix_A))
#eigen_values_A,eigen_vectors_A=tf.linalg.eigh(e_matrix_A)
# linalg = linear algebra
# eigh = decomposition of self adjoint metrices

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
Matrix A: 
[[0.9362874  0.11518371]
 [0.49891353 0.763585  ]] 
Eigen Vectors:
[[-0.64399415  0.7650304 ]
 [ 0.7650304   0.64399415]]

Eigen Values:
[0.343605  1.3562673]

